---
server:
  port: 8080
  contextPath: /SpringBootCRUDApp
spring:
  profiles: default
datasource:
  sampleapp:
    url: jdbc:mysql://demords.chedqqbjsvlg.us-east-1.rds.amazonaws.com:3306/websystique
    username: admin
    password: rean1234
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
